FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app
COPY ../.. .

RUN ./gradlew :admin:bootJar --no-daemon

FROM eclipse-temurin:21-jdk

WORKDIR /app
COPY --from=builder /app/admin/build/libs/farm2Pot-admin.jar farm2Pot-admin.jar

ENTRYPOINT ["java", "-jar", "/app/farm2Pot-admin.jar"]
