# SUBSCRIPTION DEV - backend server port
server:
  port: 18083

# project
farm2pot:
  core-service:
    url: http://localhost:18080

# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost:23306/farm2pot
    #    ?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: farm2pot
    password: farm2pot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 16379

kafka:
  bootstrap-servers: localhost:19092

