server:
  port: 18080

spring:
  application:
    name: core-service
  datasource:
    url: jdbc:mysql://localhost:13306/farm2Pot
    username: farm2Pot
    password: farm2Pot
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 16379

logging:
  level:
    com.farm2pot: DEBUG