server:
  port: 18082

spring:
  application:
    name: admin-service
  datasource:
    url: jdbc:mysql://localhost:13306/farm2Pot
    username: farm2Pot
    password: farm2Pot
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: localhost
      port: 16379

farm2pot:
  core-service:
    url: http://localhost:18080

logging:
  level:
    com.farm2pot: DEBUG