# GATEWAY DEV - backend server port
server:
  port: 19080

spring:
  application:
    name: gateway-service

# Route 설정
routes:
  core:
    url: http://localhost:18080
    path: /api/core/**
  user:
    url: http://localhost:18081
    path: /api/user/**
  admin:
    url: http://localhost:18082
    path: /api/admin/**
  subscription:
    url: http://localhost:18083
    path: /api/subscription/**

# frontend server host
frontend:
  host: localhost

logging:
  level:
    com.farm2pot: DEBUG
    org.springframework: WARN