# CORE DEV - backend server port
server:
  port: 18080

# Spring
spring:
  datasource:
    url: jdbc:mysql://localhost:23306/farm2pot
    username: farm2pot
    password: farm2pot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 16379

kafka:
  bootstrap-servers: localhost:19092

