FROM eclipse-temurin:21-jdk AS builder

WORKDIR /app
COPY ../.. .

RUN ./gradlew :subscription:bootJar --no-daemon

FROM eclipse-temurin:21-jdk

WORKDIR /app
COPY --from=builder /app/subscription/build/libs/farm2Pot-sub.jar farm2Pot-sub.jar

ENTRYPOINT ["java", "-jar", "/app/farm2Pot-sub.jar"]
